24 - Endpoint de Jogos da comunidade
lamiautfpr/ICT01-2019-backend-E-Battle pull request #30
Opened 2022-08-23 19:42 UTC by ErikHenrique09

foi criado um endpoint que permite realizar a busca de jogos de todos os jogadores, com um filtro de parametros opcionais

parametros: 
 - name: string
 - language: id number
 - category: id number 
 - limit: number (por padrão é 5)

2022-08-24 11:28 UTC, ErikHenrique09 commented on src/routes/games/games.controller.ts
> +  @UseGuards(JwtAuthGuard)
Criação do endpoint em games.controller.ts

2022-08-24 12:28 UTC, henriquepacheco26 approved these changes

2022-08-28 05:17 UTC, Guilherme-Veras requested changes

2022-08-28 05:17 UTC, Guilherme-Veras commented on src/routes/games/games.controller.ts
> +      throw new NotFoundException('Nenhum jogo corresponde a este filtro');
Não é necessária essa verificação e erro, caso nenhum seja encontrado pode apenas retornar um array vazio

2022-08-28 05:17 UTC, Guilherme-Veras commented on src/routes/games/games.dto.ts
> +export class QueryParamsDto {
Está faltando a verificação de tipo, ex.: @IsString()

2022-08-28 05:17 UTC, Guilherme-Veras commented on src/routes/games/games.service.ts
> +        name: ILike(`%${name ?? ''}`),
Está faltando um '%' depois do nome, pois se for feita a busca por 'car' e só vai encontrar nomes que finalização com 'car' e não qualquer nome que contenha 'car', por exemplo: 'carro'.

2022-08-28 17:38 UTC, ErikHenrique09 commented on src/routes/games/games.controller.ts
> +      throw new NotFoundException('Nenhum jogo corresponde a este filtro');
Esqueci de te perguntar sobre esse topico, fiquei na duvida entre o array vazio e alguma mensagem, vou alterar

2022-08-28 18:44 UTC, ErikHenrique09 commented
Removi o retorno da mensagem 'Nenhum jogo encontrado', adicionei as verificações de tipo assim como a descrição dos parâmetros, e alterei a query de pesquisa do parâmetro name.

2022-08-30 20:58 UTC, guilhermeV20 approved these changes

2022-08-30 20:59 UTC, Guilherme-Veras approved these changes

2022-08-30 20:59 UTC, merged